"""novas colunas na tabela usuario

Revision ID: 1be85e9db169
Revises: 87efa865baa7
Create Date: 2024-10-11 21:23:21.126432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1be85e9db169'
down_revision: Union[str, None] = '87efa865baa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('conta_pro', sa.Boolean(), nullable=True))
    op.add_column('usuarios', sa.Column('limite_diario_publicacoes', sa.Integer(), nullable=True))
    op.add_column('usuarios', sa.Column('data_ativacao_pro', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'data_ativacao_pro')
    op.drop_column('usuarios', 'limite_diario_publicacoes')
    op.drop_column('usuarios', 'conta_pro')
    # ### end Alembic commands ###
