"""adicionei coluna saldo no usuario

Revision ID: 25e95cb0294a
Revises: 4c17384b01ca
Create Date: 2024-09-13 01:32:44.217523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25e95cb0294a'
down_revision: Union[str, None] = '4c17384b01ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('saldo', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'saldo')
    # ### end Alembic commands ###
