"""Create users table

Revision ID: 31d4cc07c50d
Revises: 4ae349e8ae24
Create Date: 2024-10-08 04:25:49.343836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31d4cc07c50d'
down_revision: Union[str, None] = '4ae349e8ae24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('aceito_pelo_vendedor', sa.Boolean(), nullable=True))
    op.add_column('pedido', sa.Column('recebido_pelo_cliente', sa.Boolean(), nullable=True))
    op.add_column('pedido', sa.Column('pagamento_confirmado', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedido', 'pagamento_confirmado')
    op.drop_column('pedido', 'recebido_pelo_cliente')
    op.drop_column('pedido', 'aceito_pelo_vendedor')
    # ### end Alembic commands ###
