"""Create users table

Revision ID: 4ae349e8ae24
Revises: 
Create Date: 2024-10-07 23:42:01.449601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ae349e8ae24'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_usuario', sa.Column('nacionalidade', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info_usuario', 'nacionalidade')
    # ### end Alembic commands ###
