"""adicionei uma coluna produto

Revision ID: 6c8bade7ad05
Revises: 
Create Date: 2024-09-18 04:02:33.893056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c8bade7ad05'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_produto_like_id', table_name='produto_like')
    op.drop_table('produto_like')
    op.add_column('produto', sa.Column('promocao_expira_em', sa.DateTime(), nullable=True))
    op.drop_column('produto', 'data_publicacao')
    op.drop_column('produto', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('data', sa.DATETIME(), nullable=True))
    op.add_column('produto', sa.Column('data_publicacao', sa.DATETIME(), nullable=True))
    op.drop_column('produto', 'promocao_expira_em')
    op.create_table('produto_like',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('produto_id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produto_id', 'usuario_id', name='unique_like_per_user')
    )
    op.create_index('ix_produto_like_id', 'produto_like', ['id'], unique=False)
    # ### end Alembic commands ###
