"""novas colunas na tabela usuario

Revision ID: 797a0a5bfc96
Revises: 1be85e9db169
Create Date: 2024-10-11 22:13:48.596242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '797a0a5bfc96'
down_revision: Union[str, None] = '1be85e9db169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_produto_slug'), 'produto', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produto_slug'), table_name='produto')
    op.drop_column('produto', 'slug')
    # ### end Alembic commands ###
