"""adicionei uma coluna produto

Revision ID: 864895f26850
Revises: 6c8bade7ad05
Create Date: 2024-09-18 04:04:11.673978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '864895f26850'
down_revision: Union[str, None] = '6c8bade7ad05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('data_publicacao', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produto', 'data_publicacao')
    # ### end Alembic commands ###
