"""Create users table

Revision ID: 94973753d199
Revises: 31d4cc07c50d
Create Date: 2024-10-09 21:07:20.971867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94973753d199'
down_revision: Union[str, None] = '31d4cc07c50d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_usuario', sa.Column('sexo', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info_usuario', 'sexo')
    # ### end Alembic commands ###
