"""novas tabelas wallet

Revision ID: 964b3c954365
Revises: 797a0a5bfc96
Create Date: 2024-10-15 03:26:18.510103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '964b3c954365'
down_revision: Union[str, None] = '797a0a5bfc96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('saldo_principal', sa.DECIMAL(), nullable=True),
    sa.Column('saldo_congelado', sa.DECIMAL(), nullable=True),
    sa.Column('bonus', sa.DECIMAL(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_wallet_id'), 'wallet', ['id'], unique=False)
    op.add_column('pedido', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.add_column('pedido', sa.Column('data_aceite', sa.DateTime(), nullable=True))
    op.add_column('pedido', sa.Column('data_envio', sa.DateTime(), nullable=True))
    op.add_column('pedido', sa.Column('data_entrega', sa.DateTime(), nullable=True))
    op.drop_constraint(None, 'pedido', type_='foreignkey')
    op.create_foreign_key(None, 'pedido', 'usuarios', ['customer_id'], ['id'])
    op.drop_column('pedido', 'CustomerID')
    op.drop_column('pedido', 'pagamento_confirmado')
    op.drop_column('usuarios', 'saldo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('saldo', sa.FLOAT(), nullable=True))
    op.add_column('pedido', sa.Column('pagamento_confirmado', sa.BOOLEAN(), nullable=True))
    op.add_column('pedido', sa.Column('CustomerID', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'pedido', type_='foreignkey')
    op.create_foreign_key(None, 'pedido', 'usuarios', ['CustomerID'], ['id'])
    op.drop_column('pedido', 'data_entrega')
    op.drop_column('pedido', 'data_envio')
    op.drop_column('pedido', 'data_aceite')
    op.drop_column('pedido', 'customer_id')
    op.drop_index(op.f('ix_wallet_id'), table_name='wallet')
    op.drop_table('wallet')
    # ### end Alembic commands ###
