"""alteracao de modelo de produto

Revision ID: 9d8456873226
Revises: 
Create Date: 2024-09-12 21:42:42.873139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d8456873226'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produto_id', 'usuario_id', name='unique_like_per_user')
    )
    op.create_index(op.f('ix_produto_like_id'), 'produto_like', ['id'], unique=False)
    op.add_column('produto', sa.Column('data_publicacao', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produto', 'data_publicacao')
    op.drop_index(op.f('ix_produto_like_id'), table_name='produto_like')
    op.drop_table('produto_like')
    # ### end Alembic commands ###
