"""adicionei uma tabela anucios

Revision ID: a6ae4fad7c56
Revises: 864895f26850
Create Date: 2024-09-18 20:29:54.930676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6ae4fad7c56'
down_revision: Union[str, None] = '864895f26850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anuncio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo_anuncio', sa.String(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('promovido_em', sa.DateTime(), nullable=True),
    sa.Column('expira_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produto_id')
    )
    op.create_index(op.f('ix_anuncio_id'), 'anuncio', ['id'], unique=False)
    op.add_column('produto', sa.Column('anuncio_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'produto', 'anuncio', ['anuncio_id'], ['id'])
    op.drop_column('produto', 'promovido')
    op.drop_column('produto', 'promocao_expira_em')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('promocao_expira_em', sa.DATETIME(), nullable=True))
    op.add_column('produto', sa.Column('promovido', sa.BOOLEAN(), nullable=True))
    op.drop_constraint(None, 'produto', type_='foreignkey')
    op.drop_column('produto', 'anuncio_id')
    op.drop_index(op.f('ix_anuncio_id'), table_name='anuncio')
    op.drop_table('anuncio')
    # ### end Alembic commands ###
