"""novas colunas na tabela usuario

Revision ID: b5fdd949920b
Revises: 
Create Date: 2024-10-17 01:56:18.821014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5fdd949920b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transacoes', sa.Column('tipo', sa.String(length=20), nullable=True))
    op.alter_column('transacoes', 'valor',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transacoes', 'valor',
               existing_type=sa.DECIMAL(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('transacoes', 'tipo')
    # ### end Alembic commands ###
